### ISSUE TITLE
Echo's messages on loop 

### ISSUE THREAD

**Issue by jackstevens298** [drdre-08/discord-selfechobot#2]
[https://prnt.sc/1vl42b8](url)   source channel

[https://prnt.sc/1vl4dqv](url)  destination channel

as you can see the bot does a loop of posting every message from the source to the destination.

**Comment by drdre-08** [comment]
Currently the bot will read the last 10 messages on the source channel and copy them.

This is no ideal as;
- If there are more than 10 messages sent since last read, then the bot will miss messages.
- If there are less than 10 messages sent since last, then the bot will duplicate messages.

Solutions;
- Keep a timestamp (or other parameter) and read last messages until this parameter matches (last read message).
- Connect a webhook to run echo code on each message sent (do not think this is possible with self bots / only with server bots). [awaitMessages](https://discord.js.org/#/docs/main/stable/class/TextChannel?scrollTo=awaitMessages) seems to do this.

**Comment by drdre-08** [comment]
[awaitMessages](https://discord.js.org/#/docs/main/stable/class/TextChannel?scrollTo=awaitMessages) does not seem to work for selfbots (signing in as user). [See](https://github.com/Rapptz/discord.py/issues/6839)

Therefore, tracking message timestamps have been implemented [here](https://github.com/drdre-08/discord-selfechobot/pull/3).
